language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
env:
    matrix:
        - GROUP=python
matrix:
    include:
        - python: 3.5
          env:
            - GROUP=js
            - BROWSER=firefox
        - python: 3.5
          sudo: required
          env:
            - GROUP=js
            - BROWSER=chrome_travis
cache:
    pip: true
    directories:
        - nbdime/webapp/node_modules # NPM packages
        - nbdime-web/node_modules # NPM packages
before_install:
    - nvm install 4
    - pip install -r requirements.txt
    - pip install pytest
    - pip install pytest-cov
    - 'if [[ $GROUP == python ]]; then pip install codecov; fi'
    - 'if [[ $GROUP == js ]]; then npm install -g codecov; fi'
install:
    - 'if [[ $GROUP == python ]]; then pip install -e ./; fi'
    - 'if [[ $GROUP == js ]]; then cd ./nbdime-web; fi'
    - 'if [[ $GROUP == js ]]; then npm install; fi'
before_script:
    # Set up a virtual screen for browser testing:
    - 'if [[ $GROUP == js && $BROWSER == chrome_travis ]]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb ; fi'
    - 'if [[ $GROUP == js && $BROWSER == chrome_travis ]]; then $ sudo dpkg -i google-chrome-stable_current_amd64.deb ; fi'
    - 'if [[ $GROUP == js ]]; then export CHROME_BIN=google-chrome-stable; fi'
    - 'if [[ $GROUP == js ]]; then export DISPLAY=:99.0; fi'
    - 'if [[ $GROUP == js ]]; then sh -e /etc/init.d/xvfb start; fi'
script:
    - 'if [[ $GROUP == python ]]; then py.test -l --cov-report html --cov=nbdime; fi'
    - 'if [[ $GROUP == js ]]; then npm run test:$BROWSER; fi'
after_success:
    - 'if [[ $GROUP == js ]]; then cd ..; fi'
    - codecov
before_cache:
    # Do not cache our folder
    - rm -rf nbdime/webapp/node_modules/nbdime
    - rm -rf nbdime/webapp/node_modules/nbdime-webapp
    - rm -rf nbdime-web/node_modules/nbdime
